--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

library cells;
use cells.all;

ENTITY alu IS
PORT(
  alu_out	: INOUT STD_LOGIC_VECTOR(3 DOWNTO 0);
  cin	: IN STD_LOGIC;
  cout	: OUT STD_LOGIC;
  i	: IN STD_LOGIC_VECTOR(2 DOWNTO 0);
  ng	: OUT STD_LOGIC;
  np	: OUT STD_LOGIC;
  ovr	: OUT STD_LOGIC;
  r	: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
  s	: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
  f3	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC;
  zero	: OUT STD_LOGIC
);
END alu;

ARCHITECTURE RTL OF alu IS
  SIGNAL not_i	: STD_LOGIC_VECTOR(2 DOWNTO 0);
  SIGNAL not_r	: STD_LOGIC_VECTOR(2 DOWNTO 0);
  SIGNAL not_s	: STD_LOGIC_VECTOR(2 DOWNTO 0);
  SIGNAL xr2_x1_sig	: STD_LOGIC;
  SIGNAL xr2_x1_9_sig	: STD_LOGIC;
  SIGNAL xr2_x1_8_sig	: STD_LOGIC;
  SIGNAL xr2_x1_7_sig	: STD_LOGIC;
  SIGNAL xr2_x1_6_sig	: STD_LOGIC;
  SIGNAL xr2_x1_5_sig	: STD_LOGIC;
  SIGNAL xr2_x1_4_sig	: STD_LOGIC;
  SIGNAL xr2_x1_3_sig	: STD_LOGIC;
  SIGNAL xr2_x1_2_sig	: STD_LOGIC;
  SIGNAL xr2_x1_12_sig	: STD_LOGIC;
  SIGNAL xr2_x1_11_sig	: STD_LOGIC;
  SIGNAL xr2_x1_10_sig	: STD_LOGIC;
  SIGNAL on12_x1_sig	: STD_LOGIC;
  SIGNAL on12_x1_2_sig	: STD_LOGIC;
  SIGNAL oa2ao222_x2_sig	: STD_LOGIC;
  SIGNAL oa2a2a2a24_x2_sig	: STD_LOGIC;
  SIGNAL oa2a2a23_x2_sig	: STD_LOGIC;
  SIGNAL oa2a22_x2_sig	: STD_LOGIC;
  SIGNAL oa2a22_x2_2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_sig	: STD_LOGIC;
  SIGNAL oa22_x2_4_sig	: STD_LOGIC;
  SIGNAL oa22_x2_3_sig	: STD_LOGIC;
  SIGNAL oa22_x2_2_sig	: STD_LOGIC;
  SIGNAL o4_x2_sig	: STD_LOGIC;
  SIGNAL o3_x2_sig	: STD_LOGIC;
  SIGNAL o3_x2_9_sig	: STD_LOGIC;
  SIGNAL o3_x2_8_sig	: STD_LOGIC;
  SIGNAL o3_x2_7_sig	: STD_LOGIC;
  SIGNAL o3_x2_6_sig	: STD_LOGIC;
  SIGNAL o3_x2_5_sig	: STD_LOGIC;
  SIGNAL o3_x2_4_sig	: STD_LOGIC;
  SIGNAL o3_x2_3_sig	: STD_LOGIC;
  SIGNAL o3_x2_2_sig	: STD_LOGIC;
  SIGNAL o3_x2_12_sig	: STD_LOGIC;
  SIGNAL o3_x2_11_sig	: STD_LOGIC;
  SIGNAL o3_x2_10_sig	: STD_LOGIC;
  SIGNAL o2_x2_sig	: STD_LOGIC;
  SIGNAL o2_x2_9_sig	: STD_LOGIC;
  SIGNAL o2_x2_8_sig	: STD_LOGIC;
  SIGNAL o2_x2_7_sig	: STD_LOGIC;
  SIGNAL o2_x2_6_sig	: STD_LOGIC;
  SIGNAL o2_x2_5_sig	: STD_LOGIC;
  SIGNAL o2_x2_4_sig	: STD_LOGIC;
  SIGNAL o2_x2_3_sig	: STD_LOGIC;
  SIGNAL o2_x2_2_sig	: STD_LOGIC;
  SIGNAL o2_x2_13_sig	: STD_LOGIC;
  SIGNAL o2_x2_12_sig	: STD_LOGIC;
  SIGNAL o2_x2_11_sig	: STD_LOGIC;
  SIGNAL o2_x2_10_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_3_sig	: STD_LOGIC;
  SIGNAL nxr2_x1_2_sig	: STD_LOGIC;
  SIGNAL not_cin	: STD_LOGIC;
  SIGNAL not_aux97	: STD_LOGIC;
  SIGNAL not_aux95	: STD_LOGIC;
  SIGNAL not_aux93	: STD_LOGIC;
  SIGNAL not_aux9	: STD_LOGIC;
  SIGNAL not_aux89	: STD_LOGIC;
  SIGNAL not_aux81	: STD_LOGIC;
  SIGNAL not_aux80	: STD_LOGIC;
  SIGNAL not_aux8	: STD_LOGIC;
  SIGNAL not_aux79	: STD_LOGIC;
  SIGNAL not_aux78	: STD_LOGIC;
  SIGNAL not_aux77	: STD_LOGIC;
  SIGNAL not_aux76	: STD_LOGIC;
  SIGNAL not_aux74	: STD_LOGIC;
  SIGNAL not_aux7	: STD_LOGIC;
  SIGNAL not_aux69	: STD_LOGIC;
  SIGNAL not_aux68	: STD_LOGIC;
  SIGNAL not_aux67	: STD_LOGIC;
  SIGNAL not_aux63	: STD_LOGIC;
  SIGNAL not_aux62	: STD_LOGIC;
  SIGNAL not_aux61	: STD_LOGIC;
  SIGNAL not_aux60	: STD_LOGIC;
  SIGNAL not_aux56	: STD_LOGIC;
  SIGNAL not_aux54	: STD_LOGIC;
  SIGNAL not_aux52	: STD_LOGIC;
  SIGNAL not_aux50	: STD_LOGIC;
  SIGNAL not_aux5	: STD_LOGIC;
  SIGNAL not_aux49	: STD_LOGIC;
  SIGNAL not_aux48	: STD_LOGIC;
  SIGNAL not_aux47	: STD_LOGIC;
  SIGNAL not_aux43	: STD_LOGIC;
  SIGNAL not_aux42	: STD_LOGIC;
  SIGNAL not_aux41	: STD_LOGIC;
  SIGNAL not_aux40	: STD_LOGIC;
  SIGNAL not_aux4	: STD_LOGIC;
  SIGNAL not_aux39	: STD_LOGIC;
  SIGNAL not_aux38	: STD_LOGIC;
  SIGNAL not_aux37	: STD_LOGIC;
  SIGNAL not_aux33	: STD_LOGIC;
  SIGNAL not_aux32	: STD_LOGIC;
  SIGNAL not_aux31	: STD_LOGIC;
  SIGNAL not_aux3	: STD_LOGIC;
  SIGNAL not_aux28	: STD_LOGIC;
  SIGNAL not_aux24	: STD_LOGIC;
  SIGNAL not_aux23	: STD_LOGIC;
  SIGNAL not_aux22	: STD_LOGIC;
  SIGNAL not_aux21	: STD_LOGIC;
  SIGNAL not_aux20	: STD_LOGIC;
  SIGNAL not_aux19	: STD_LOGIC;
  SIGNAL not_aux17	: STD_LOGIC;
  SIGNAL not_aux16	: STD_LOGIC;
  SIGNAL not_aux15	: STD_LOGIC;
  SIGNAL not_aux13	: STD_LOGIC;
  SIGNAL not_aux115	: STD_LOGIC;
  SIGNAL not_aux113	: STD_LOGIC;
  SIGNAL not_aux112	: STD_LOGIC;
  SIGNAL not_aux110	: STD_LOGIC;
  SIGNAL not_aux108	: STD_LOGIC;
  SIGNAL not_aux107	: STD_LOGIC;
  SIGNAL not_aux106	: STD_LOGIC;
  SIGNAL not_aux105	: STD_LOGIC;
  SIGNAL not_aux104	: STD_LOGIC;
  SIGNAL not_aux103	: STD_LOGIC;
  SIGNAL not_aux102	: STD_LOGIC;
  SIGNAL not_aux101	: STD_LOGIC;
  SIGNAL not_aux1	: STD_LOGIC;
  SIGNAL not_aux0	: STD_LOGIC;
  SIGNAL noa3ao322_x1_sig	: STD_LOGIC;
  SIGNAL noa22_x1_sig	: STD_LOGIC;
  SIGNAL noa22_x1_5_sig	: STD_LOGIC;
  SIGNAL noa22_x1_4_sig	: STD_LOGIC;
  SIGNAL noa22_x1_3_sig	: STD_LOGIC;
  SIGNAL noa22_x1_2_sig	: STD_LOGIC;
  SIGNAL no4_x1_sig	: STD_LOGIC;
  SIGNAL no4_x1_5_sig	: STD_LOGIC;
  SIGNAL no4_x1_4_sig	: STD_LOGIC;
  SIGNAL no4_x1_3_sig	: STD_LOGIC;
  SIGNAL no4_x1_2_sig	: STD_LOGIC;
  SIGNAL no3_x1_sig	: STD_LOGIC;
  SIGNAL no3_x1_7_sig	: STD_LOGIC;
  SIGNAL no3_x1_6_sig	: STD_LOGIC;
  SIGNAL no3_x1_5_sig	: STD_LOGIC;
  SIGNAL no3_x1_4_sig	: STD_LOGIC;
  SIGNAL no3_x1_3_sig	: STD_LOGIC;
  SIGNAL no3_x1_2_sig	: STD_LOGIC;
  SIGNAL no2_x1_sig	: STD_LOGIC;
  SIGNAL no2_x1_9_sig	: STD_LOGIC;
  SIGNAL no2_x1_8_sig	: STD_LOGIC;
  SIGNAL no2_x1_7_sig	: STD_LOGIC;
  SIGNAL no2_x1_6_sig	: STD_LOGIC;
  SIGNAL no2_x1_5_sig	: STD_LOGIC;
  SIGNAL no2_x1_4_sig	: STD_LOGIC;
  SIGNAL no2_x1_3_sig	: STD_LOGIC;
  SIGNAL no2_x1_2_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao2o22_x1_2_sig	: STD_LOGIC;
  SIGNAL nao22_x1_sig	: STD_LOGIC;
  SIGNAL nao22_x1_9_sig	: STD_LOGIC;
  SIGNAL nao22_x1_8_sig	: STD_LOGIC;
  SIGNAL nao22_x1_7_sig	: STD_LOGIC;
  SIGNAL nao22_x1_6_sig	: STD_LOGIC;
  SIGNAL nao22_x1_5_sig	: STD_LOGIC;
  SIGNAL nao22_x1_4_sig	: STD_LOGIC;
  SIGNAL nao22_x1_3_sig	: STD_LOGIC;
  SIGNAL nao22_x1_2_sig	: STD_LOGIC;
  SIGNAL na4_x1_sig	: STD_LOGIC;
  SIGNAL na4_x1_3_sig	: STD_LOGIC;
  SIGNAL na4_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_sig	: STD_LOGIC;
  SIGNAL na3_x1_9_sig	: STD_LOGIC;
  SIGNAL na3_x1_8_sig	: STD_LOGIC;
  SIGNAL na3_x1_7_sig	: STD_LOGIC;
  SIGNAL na3_x1_6_sig	: STD_LOGIC;
  SIGNAL na3_x1_5_sig	: STD_LOGIC;
  SIGNAL na3_x1_4_sig	: STD_LOGIC;
  SIGNAL na3_x1_3_sig	: STD_LOGIC;
  SIGNAL na3_x1_2_sig	: STD_LOGIC;
  SIGNAL na3_x1_20_sig	: STD_LOGIC;
  SIGNAL na3_x1_19_sig	: STD_LOGIC;
  SIGNAL na3_x1_18_sig	: STD_LOGIC;
  SIGNAL na3_x1_17_sig	: STD_LOGIC;
  SIGNAL na3_x1_16_sig	: STD_LOGIC;
  SIGNAL na3_x1_15_sig	: STD_LOGIC;
  SIGNAL na3_x1_14_sig	: STD_LOGIC;
  SIGNAL na3_x1_13_sig	: STD_LOGIC;
  SIGNAL na3_x1_12_sig	: STD_LOGIC;
  SIGNAL na3_x1_11_sig	: STD_LOGIC;
  SIGNAL na3_x1_10_sig	: STD_LOGIC;
  SIGNAL na2_x1_sig	: STD_LOGIC;
  SIGNAL na2_x1_9_sig	: STD_LOGIC;
  SIGNAL na2_x1_8_sig	: STD_LOGIC;
  SIGNAL na2_x1_7_sig	: STD_LOGIC;
  SIGNAL na2_x1_6_sig	: STD_LOGIC;
  SIGNAL na2_x1_5_sig	: STD_LOGIC;
  SIGNAL na2_x1_4_sig	: STD_LOGIC;
  SIGNAL na2_x1_3_sig	: STD_LOGIC;
  SIGNAL na2_x1_2_sig	: STD_LOGIC;
  SIGNAL na2_x1_11_sig	: STD_LOGIC;
  SIGNAL na2_x1_10_sig	: STD_LOGIC;
  SIGNAL mx3_x2_sig	: STD_LOGIC;
  SIGNAL mx3_x2_6_sig	: STD_LOGIC;
  SIGNAL mx3_x2_5_sig	: STD_LOGIC;
  SIGNAL mx3_x2_4_sig	: STD_LOGIC;
  SIGNAL mx3_x2_3_sig	: STD_LOGIC;
  SIGNAL mx3_x2_2_sig	: STD_LOGIC;
  SIGNAL mx2_x2_sig	: STD_LOGIC;
  SIGNAL mx2_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_sig	: STD_LOGIC;
  SIGNAL inv_x2_9_sig	: STD_LOGIC;
  SIGNAL inv_x2_8_sig	: STD_LOGIC;
  SIGNAL inv_x2_7_sig	: STD_LOGIC;
  SIGNAL inv_x2_6_sig	: STD_LOGIC;
  SIGNAL inv_x2_5_sig	: STD_LOGIC;
  SIGNAL inv_x2_4_sig	: STD_LOGIC;
  SIGNAL inv_x2_3_sig	: STD_LOGIC;
  SIGNAL inv_x2_2_sig	: STD_LOGIC;
  SIGNAL inv_x2_12_sig	: STD_LOGIC;
  SIGNAL inv_x2_11_sig	: STD_LOGIC;
  SIGNAL inv_x2_10_sig	: STD_LOGIC;
  SIGNAL aux99	: STD_LOGIC;
  SIGNAL aux98	: STD_LOGIC;
  SIGNAL aux91	: STD_LOGIC;
  SIGNAL aux77	: STD_LOGIC;
  SIGNAL aux75	: STD_LOGIC;
  SIGNAL aux70	: STD_LOGIC;
  SIGNAL aux7	: STD_LOGIC;
  SIGNAL aux68	: STD_LOGIC;
  SIGNAL aux63	: STD_LOGIC;
  SIGNAL aux51	: STD_LOGIC;
  SIGNAL aux43	: STD_LOGIC;
  SIGNAL aux42	: STD_LOGIC;
  SIGNAL aux4	: STD_LOGIC;
  SIGNAL aux39	: STD_LOGIC;
  SIGNAL aux32	: STD_LOGIC;
  SIGNAL aux3	: STD_LOGIC;
  SIGNAL aux29	: STD_LOGIC;
  SIGNAL aux25	: STD_LOGIC;
  SIGNAL aux23	: STD_LOGIC;
  SIGNAL aux21	: STD_LOGIC;
  SIGNAL aux20	: STD_LOGIC;
  SIGNAL aux19	: STD_LOGIC;
  SIGNAL aux17	: STD_LOGIC;
  SIGNAL aux16	: STD_LOGIC;
  SIGNAL aux12	: STD_LOGIC;
  SIGNAL aux114	: STD_LOGIC;
  SIGNAL aux111	: STD_LOGIC;
  SIGNAL aux109	: STD_LOGIC;
  SIGNAL aux108	: STD_LOGIC;
  SIGNAL aux105	: STD_LOGIC;
  SIGNAL aux104	: STD_LOGIC;
  SIGNAL aux102	: STD_LOGIC;
  SIGNAL aux100	: STD_LOGIC;
  SIGNAL aux1	: STD_LOGIC;
  SIGNAL ao2o22_x2_sig	: STD_LOGIC;
  SIGNAL ao2o22_x2_2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_sig	: STD_LOGIC;
  SIGNAL ao22_x2_4_sig	: STD_LOGIC;
  SIGNAL ao22_x2_3_sig	: STD_LOGIC;
  SIGNAL ao22_x2_2_sig	: STD_LOGIC;
  SIGNAL an12_x1_sig	: STD_LOGIC;
  SIGNAL a4_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_sig	: STD_LOGIC;
  SIGNAL a3_x2_3_sig	: STD_LOGIC;
  SIGNAL a3_x2_2_sig	: STD_LOGIC;
  SIGNAL a2_x2_sig	: STD_LOGIC;
  SIGNAL a2_x2_9_sig	: STD_LOGIC;
  SIGNAL a2_x2_8_sig	: STD_LOGIC;
  SIGNAL a2_x2_7_sig	: STD_LOGIC;
  SIGNAL a2_x2_6_sig	: STD_LOGIC;
  SIGNAL a2_x2_5_sig	: STD_LOGIC;
  SIGNAL a2_x2_4_sig	: STD_LOGIC;
  SIGNAL a2_x2_3_sig	: STD_LOGIC;
  SIGNAL a2_x2_2_sig	: STD_LOGIC;
  SIGNAL a2_x2_12_sig	: STD_LOGIC;
  SIGNAL a2_x2_11_sig	: STD_LOGIC;
  SIGNAL a2_x2_10_sig	: STD_LOGIC;

  COMPONENT oa2ao222_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2a2a2a24_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  i5	: IN STD_LOGIC;
  i6	: IN STD_LOGIC;
  i7	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT inv_x2
  PORT(
  i	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT no3_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT na4_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a2_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT an12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT mx3_x2
  PORT(
  cmd0	: IN STD_LOGIC;
  cmd1	: IN STD_LOGIC;
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT mx2_x2
  PORT(
  cmd	: IN STD_LOGIC;
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT xr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2a22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nao2o22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT nxr2_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa2a2a23_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  i5	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa22_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT oa3ao322_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  i5	: IN STD_LOGIC;
  i6	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT on12_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a3_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT noa3ao322_x1
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  i4	: IN STD_LOGIC;
  i5	: IN STD_LOGIC;
  i6	: IN STD_LOGIC;
  nq	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT ao2o22_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT buf_x2
  PORT(
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT o4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

  COMPONENT a4_x2
  PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  i2	: IN STD_LOGIC;
  i3	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd	: IN STD_LOGIC;
  vss	: IN STD_LOGIC
   );
  END COMPONENT;

BEGIN
  alu_out_3_ins : oa2ao222_x2
  PORT MAP (
    i0 => oa2a2a2a24_x2_sig,
    i1 => not_i(1),
    i2 => a2_x2_12_sig,
    i3 => na3_x1_17_sig,
    i4 => i(1),
    q => alu_out(3),
    vdd => vdd,
    vss => vss
  );
  oa2a2a2a24_x2_ins : oa2a2a2a24_x2
  PORT MAP (
    i0 => not_s(2),
    i1 => na2_x1_11_sig,
    i2 => na2_x1_10_sig,
    i3 => s(2),
    i4 => not_i(0),
    i5 => o3_x2_9_sig,
    i6 => na3_x1_19_sig,
    i7 => i(0),
    q => oa2a2a2a24_x2_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_11_ins : na2_x1
  PORT MAP (
    i0 => na3_x1_20_sig,
    i1 => o3_x2_12_sig,
    nq => na2_x1_11_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_20_ins : na3_x1
  PORT MAP (
    i0 => i(0),
    i1 => aux104,
    i2 => o2_x2_13_sig,
    nq => na3_x1_20_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_13_ins : o2_x2
  PORT MAP (
    i0 => r(2),
    i1 => not_aux50,
    q => o2_x2_13_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_12_ins : o3_x2
  PORT MAP (
    i0 => i(0),
    i1 => not_aux103,
    i2 => no2_x1_9_sig,
    q => o3_x2_12_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_9_ins : no2_x1
  PORT MAP (
    i0 => not_aux40,
    i1 => not_r(2),
    nq => no2_x1_9_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_10_ins : na2_x1
  PORT MAP (
    i0 => o3_x2_11_sig,
    i1 => o3_x2_10_sig,
    nq => na2_x1_10_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_11_ins : o3_x2
  PORT MAP (
    i0 => not_aux41,
    i1 => i(0),
    i2 => not_aux104,
    q => o3_x2_11_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_10_ins : o3_x2
  PORT MAP (
    i0 => not_i(0),
    i1 => not_aux103,
    i2 => inv_x2_12_sig,
    q => o3_x2_10_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_12_ins : inv_x2
  PORT MAP (
    i => aux51,
    nq => inv_x2_12_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_9_ins : o3_x2
  PORT MAP (
    i0 => aux63,
    i1 => no4_x1_5_sig,
    i2 => no3_x1_7_sig,
    q => o3_x2_9_sig,
    vdd => vdd,
    vss => vss
  );
  no4_x1_5_ins : no4_x1
  PORT MAP (
    i0 => not_aux5,
    i1 => aux1,
    i2 => not_aux112,
    i3 => not_aux9,
    nq => no4_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  no3_x1_7_ins : no3_x1
  PORT MAP (
    i0 => aux4,
    i1 => inv_x2_11_sig,
    i2 => not_aux113,
    nq => no3_x1_7_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_11_ins : inv_x2
  PORT MAP (
    i => aux111,
    nq => inv_x2_11_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_19_ins : na3_x1
  PORT MAP (
    i0 => o2_x2_12_sig,
    i1 => na4_x1_3_sig,
    i2 => o3_x2_8_sig,
    nq => na3_x1_19_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_12_ins : o2_x2
  PORT MAP (
    i0 => not_aux16,
    i1 => not_i(2),
    q => o2_x2_12_sig,
    vdd => vdd,
    vss => vss
  );
  na4_x1_3_ins : na4_x1
  PORT MAP (
    i0 => aux111,
    i1 => aux25,
    i2 => not_aux17,
    i3 => aux21,
    nq => na4_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_8_ins : o3_x2
  PORT MAP (
    i0 => not_aux115,
    i1 => not_aux112,
    i2 => aux20,
    q => o3_x2_8_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_12_ins : a2_x2
  PORT MAP (
    i0 => na3_x1_18_sig,
    i1 => not_i(0),
    q => a2_x2_12_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_18_ins : na3_x1
  PORT MAP (
    i0 => na2_x1_9_sig,
    i1 => na4_x1_2_sig,
    i2 => na2_x1_8_sig,
    nq => na3_x1_18_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_9_ins : na2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_aux102,
    nq => na2_x1_9_sig,
    vdd => vdd,
    vss => vss
  );
  na4_x1_2_ins : na4_x1
  PORT MAP (
    i0 => not_aux17,
    i1 => aux114,
    i2 => not_aux102,
    i3 => aux108,
    nq => na4_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_8_ins : na2_x1
  PORT MAP (
    i0 => aux102,
    i1 => no4_x1_4_sig,
    nq => na2_x1_8_sig,
    vdd => vdd,
    vss => vss
  );
  no4_x1_4_ins : no4_x1
  PORT MAP (
    i0 => not_aux105,
    i1 => not_aux69,
    i2 => aux20,
    i3 => not_aux54,
    nq => no4_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_17_ins : na3_x1
  PORT MAP (
    i0 => o3_x2_7_sig,
    i1 => nao22_x1_9_sig,
    i2 => oa22_x2_4_sig,
    nq => na3_x1_17_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_7_ins : o3_x2
  PORT MAP (
    i0 => not_aux107,
    i1 => not_aux104,
    i2 => a2_x2_11_sig,
    q => o3_x2_7_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_11_ins : a2_x2
  PORT MAP (
    i0 => r(2),
    i1 => not_aux62,
    q => a2_x2_11_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_9_ins : nao22_x1
  PORT MAP (
    i0 => r(2),
    i1 => a2_x2_10_sig,
    i2 => an12_x1_sig,
    nq => nao22_x1_9_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_10_ins : a2_x2
  PORT MAP (
    i0 => not_aux62,
    i1 => not_i(2),
    q => a2_x2_10_sig,
    vdd => vdd,
    vss => vss
  );
  an12_x1_ins : an12_x1
  PORT MAP (
    i0 => o2_x2_11_sig,
    i1 => not_aux102,
    q => an12_x1_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_11_ins : o2_x2
  PORT MAP (
    i0 => s(2),
    i1 => i(0),
    q => o2_x2_11_sig,
    vdd => vdd,
    vss => vss
  );
  oa22_x2_4_ins : oa22_x2
  PORT MAP (
    i0 => o2_x2_10_sig,
    i1 => o2_x2_9_sig,
    i2 => not_i(0),
    q => oa22_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_10_ins : o2_x2
  PORT MAP (
    i0 => i(2),
    i1 => aux32,
    q => o2_x2_10_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_9_ins : o2_x2
  PORT MAP (
    i0 => not_aux102,
    i1 => not_i(2),
    q => o2_x2_9_sig,
    vdd => vdd,
    vss => vss
  );
  alu_out_2_ins : mx3_x2
  PORT MAP (
    cmd0 => not_i(1),
    cmd1 => s(2),
    i0 => mx3_x2_6_sig,
    i1 => oa2a22_x2_2_sig,
    i2 => mx3_x2_5_sig,
    q => alu_out(2),
    vdd => vdd,
    vss => vss
  );
  mx3_x2_6_ins : mx3_x2
  PORT MAP (
    cmd0 => not_s(2),
    cmd1 => not_i(0),
    i0 => mx2_x2_2_sig,
    i1 => not_aux101,
    i2 => xr2_x1_12_sig,
    q => mx3_x2_6_sig,
    vdd => vdd,
    vss => vss
  );
  mx2_x2_2_ins : mx2_x2
  PORT MAP (
    cmd => i(0),
    i0 => inv_x2_10_sig,
    i1 => aux109,
    q => mx2_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_10_ins : inv_x2
  PORT MAP (
    i => not_aux101,
    nq => inv_x2_10_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_12_ins : xr2_x1
  PORT MAP (
    i0 => r(2),
    i1 => i(2),
    q => xr2_x1_12_sig,
    vdd => vdd,
    vss => vss
  );
  oa2a22_x2_2_ins : oa2a22_x2
  PORT MAP (
    i0 => not_i(0),
    i1 => xr2_x1_11_sig,
    i2 => xr2_x1_10_sig,
    i3 => i(0),
    q => oa2a22_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_11_ins : xr2_x1
  PORT MAP (
    i0 => aux99,
    i1 => r(2),
    q => xr2_x1_11_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_10_ins : xr2_x1
  PORT MAP (
    i0 => aux100,
    i1 => r(2),
    q => xr2_x1_10_sig,
    vdd => vdd,
    vss => vss
  );
  mx3_x2_5_ins : mx3_x2
  PORT MAP (
    cmd0 => i(0),
    cmd1 => not_r(2),
    i0 => nao2o22_x1_6_sig,
    i1 => inv_x2_8_sig,
    i2 => inv_x2_7_sig,
    q => mx3_x2_5_sig,
    vdd => vdd,
    vss => vss
  );
  nao2o22_x1_6_ins : nao2o22_x1
  PORT MAP (
    i0 => not_r(2),
    i1 => inv_x2_9_sig,
    i2 => not_aux80,
    i3 => r(2),
    nq => nao2o22_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_9_ins : inv_x2
  PORT MAP (
    i => aux99,
    nq => inv_x2_9_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_8_ins : inv_x2
  PORT MAP (
    i => aux100,
    nq => inv_x2_8_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_7_ins : inv_x2
  PORT MAP (
    i => not_aux81,
    nq => inv_x2_7_sig,
    vdd => vdd,
    vss => vss
  );
  alu_out_1_ins : mx3_x2
  PORT MAP (
    cmd0 => not_i(1),
    cmd1 => not_i(0),
    i0 => mx3_x2_4_sig,
    i1 => mx3_x2_3_sig,
    i2 => mx3_x2_2_sig,
    q => alu_out(1),
    vdd => vdd,
    vss => vss
  );
  mx3_x2_4_ins : mx3_x2
  PORT MAP (
    cmd0 => not_i(0),
    cmd1 => not_i(2),
    i0 => oa2a22_x2_sig,
    i1 => nao2o22_x1_5_sig,
    i2 => inv_x2_6_sig,
    q => mx3_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  oa2a22_x2_ins : oa2a22_x2
  PORT MAP (
    i0 => i(2),
    i1 => aux98,
    i2 => not_aux4,
    i3 => not_i(2),
    q => oa2a22_x2_sig,
    vdd => vdd,
    vss => vss
  );
  nao2o22_x1_5_ins : nao2o22_x1
  PORT MAP (
    i0 => not_cin,
    i1 => not_aux95,
    i2 => not_aux97,
    i3 => cin,
    nq => nao2o22_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_6_ins : inv_x2
  PORT MAP (
    i => aux98,
    nq => inv_x2_6_sig,
    vdd => vdd,
    vss => vss
  );
  mx3_x2_3_ins : mx3_x2
  PORT MAP (
    cmd0 => not_i(2),
    cmd1 => cin,
    i0 => aux1,
    i1 => xr2_x1_8_sig,
    i2 => xr2_x1_6_sig,
    q => mx3_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_8_ins : xr2_x1
  PORT MAP (
    i0 => aux7,
    i1 => xr2_x1_9_sig,
    q => xr2_x1_8_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_9_ins : xr2_x1
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    q => xr2_x1_9_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_6_ins : xr2_x1
  PORT MAP (
    i0 => xr2_x1_7_sig,
    i1 => not_aux3,
    q => xr2_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_7_ins : xr2_x1
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    q => xr2_x1_7_sig,
    vdd => vdd,
    vss => vss
  );
  mx3_x2_2_ins : mx3_x2
  PORT MAP (
    cmd0 => not_i(2),
    cmd1 => not_cin,
    i0 => aux17,
    i1 => not_aux95,
    i2 => not_aux97,
    q => mx3_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  alu_out_0_ins : mx3_x2
  PORT MAP (
    cmd0 => i(1),
    cmd1 => i(0),
    i0 => mx3_x2_sig,
    i1 => nao2o22_x1_4_sig,
    i2 => nxr2_x1_3_sig,
    q => alu_out(0),
    vdd => vdd,
    vss => vss
  );
  mx3_x2_ins : mx3_x2
  PORT MAP (
    cmd0 => not_i(0),
    cmd1 => not_i(2),
    i0 => mx2_x2_sig,
    i1 => not_aux93,
    i2 => not_aux3,
    q => mx3_x2_sig,
    vdd => vdd,
    vss => vss
  );
  mx2_x2_ins : mx2_x2
  PORT MAP (
    cmd => i(2),
    i0 => inv_x2_5_sig,
    i1 => not_aux19,
    q => mx2_x2_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_5_ins : inv_x2
  PORT MAP (
    i => not_aux93,
    nq => inv_x2_5_sig,
    vdd => vdd,
    vss => vss
  );
  nao2o22_x1_4_ins : nao2o22_x1
  PORT MAP (
    i0 => not_i(2),
    i1 => xr2_x1_5_sig,
    i2 => not_aux7,
    i3 => i(2),
    nq => nao2o22_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_5_ins : xr2_x1
  PORT MAP (
    i0 => r(0),
    i1 => s(0),
    q => xr2_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  nxr2_x1_3_ins : nxr2_x1
  PORT MAP (
    i0 => xr2_x1_4_sig,
    i1 => o2_x2_8_sig,
    nq => nxr2_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_4_ins : xr2_x1
  PORT MAP (
    i0 => s(0),
    i1 => r(0),
    q => xr2_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_8_ins : o2_x2
  PORT MAP (
    i0 => cin,
    i1 => i(2),
    q => o2_x2_8_sig,
    vdd => vdd,
    vss => vss
  );
  cout_ins : mx3_x2
  PORT MAP (
    cmd0 => i(1),
    cmd1 => s(2),
    i0 => oa2a2a23_x2_sig,
    i1 => oa22_x2_3_sig,
    i2 => oa2ao222_x2_sig,
    q => cout,
    vdd => vdd,
    vss => vss
  );
  oa2a2a23_x2_ins : oa2a2a23_x2
  PORT MAP (
    i0 => na2_x1_5_sig,
    i1 => s(2),
    i2 => i(0),
    i3 => na3_x1_14_sig,
    i4 => na3_x1_13_sig,
    i5 => not_i(0),
    q => oa2a2a23_x2_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_5_ins : na2_x1
  PORT MAP (
    i0 => na3_x1_16_sig,
    i1 => na3_x1_15_sig,
    nq => na2_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_16_ins : na3_x1
  PORT MAP (
    i0 => i(0),
    i1 => not_aux43,
    i2 => na2_x1_7_sig,
    nq => na3_x1_16_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_7_ins : na2_x1
  PORT MAP (
    i0 => r(2),
    i1 => not_aux81,
    nq => na2_x1_7_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_15_ins : na3_x1
  PORT MAP (
    i0 => not_i(0),
    i1 => not_aux33,
    i2 => na2_x1_6_sig,
    nq => na3_x1_15_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_6_ins : na2_x1
  PORT MAP (
    i0 => not_aux80,
    i1 => not_r(2),
    nq => na2_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_14_ins : na3_x1
  PORT MAP (
    i0 => not_aux16,
    i1 => o2_x2_7_sig,
    i2 => o2_x2_6_sig,
    nq => na3_x1_14_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_7_ins : o2_x2
  PORT MAP (
    i0 => not_aux115,
    i1 => not_aux110,
    q => o2_x2_7_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_6_ins : o2_x2
  PORT MAP (
    i0 => not_aux49,
    i1 => not_i(2),
    q => o2_x2_6_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_13_ins : na3_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => o3_x2_6_sig,
    i2 => na2_x1_4_sig,
    nq => na3_x1_13_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_6_ins : o3_x2
  PORT MAP (
    i0 => not_aux108,
    i1 => not_aux39,
    i2 => not_aux79,
    q => o3_x2_6_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_4_ins : na2_x1
  PORT MAP (
    i0 => i(2),
    i1 => aux39,
    nq => na2_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  oa22_x2_3_ins : oa22_x2
  PORT MAP (
    i0 => nao2o22_x1_3_sig,
    i1 => not_i(0),
    i2 => no3_x1_6_sig,
    q => oa22_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  nao2o22_x1_3_ins : nao2o22_x1
  PORT MAP (
    i0 => r(2),
    i1 => nxr2_x1_2_sig,
    i2 => not_aux89,
    i3 => not_r(2),
    nq => nao2o22_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  nxr2_x1_2_ins : nxr2_x1
  PORT MAP (
    i0 => aux42,
    i1 => i(2),
    nq => nxr2_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  no3_x1_6_ins : no3_x1
  PORT MAP (
    i0 => not_i(0),
    i1 => noa22_x1_5_sig,
    i2 => not_aux74,
    nq => no3_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  noa22_x1_5_ins : noa22_x1
  PORT MAP (
    i0 => not_aux32,
    i1 => i(2),
    i2 => aux91,
    nq => noa22_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  oa2ao222_x2_ins : oa2ao222_x2
  PORT MAP (
    i0 => nao2o22_x1_2_sig,
    i1 => not_i(0),
    i2 => na3_x1_12_sig,
    i3 => no4_x1_3_sig,
    i4 => i(0),
    q => oa2ao222_x2_sig,
    vdd => vdd,
    vss => vss
  );
  nao2o22_x1_2_ins : nao2o22_x1
  PORT MAP (
    i0 => not_r(2),
    i1 => not_aux56,
    i2 => not_aux89,
    i3 => r(2),
    nq => nao2o22_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_12_ins : na3_x1
  PORT MAP (
    i0 => not_aux105,
    i1 => not_aux63,
    i2 => inv_x2_4_sig,
    nq => na3_x1_12_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_4_ins : inv_x2
  PORT MAP (
    i => aux91,
    nq => inv_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  no4_x1_3_ins : no4_x1
  PORT MAP (
    i0 => a2_x2_9_sig,
    i1 => not_r(2),
    i2 => not_aux79,
    i3 => not_i(2),
    nq => no4_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_9_ins : a2_x2
  PORT MAP (
    i0 => cin,
    i1 => not_aux38,
    q => a2_x2_9_sig,
    vdd => vdd,
    vss => vss
  );
  ng_ins : oa3ao322_x2
  PORT MAP (
    i0 => na2_x1_3_sig,
    i1 => i(1),
    i2 => na3_x1_9_sig,
    i3 => noa22_x1_3_sig,
    i4 => noa22_x1_2_sig,
    i5 => not_s(2),
    i6 => noa22_x1_sig,
    q => ng,
    vdd => vdd,
    vss => vss
  );
  na2_x1_3_ins : na2_x1
  PORT MAP (
    i0 => na3_x1_11_sig,
    i1 => na3_x1_10_sig,
    nq => na2_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_11_ins : na3_x1
  PORT MAP (
    i0 => not_i(0),
    i1 => not_aux42,
    i2 => o3_x2_5_sig,
    nq => na3_x1_11_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_5_ins : o3_x2
  PORT MAP (
    i0 => not_aux28,
    i1 => not_aux24,
    i2 => not_r(2),
    q => o3_x2_5_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_10_ins : na3_x1
  PORT MAP (
    i0 => o2_x2_5_sig,
    i1 => a2_x2_8_sig,
    i2 => o3_x2_4_sig,
    nq => na3_x1_10_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_5_ins : o2_x2
  PORT MAP (
    i0 => i(2),
    i1 => not_aux8,
    q => o2_x2_5_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_8_ins : a2_x2
  PORT MAP (
    i0 => i(0),
    i1 => not_aux32,
    q => a2_x2_8_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_4_ins : o3_x2
  PORT MAP (
    i0 => aux109,
    i1 => not_aux8,
    i2 => aux12,
    q => o3_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_9_ins : na3_x1
  PORT MAP (
    i0 => not_s(2),
    i1 => nao22_x1_8_sig,
    i2 => nao22_x1_7_sig,
    nq => na3_x1_9_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_8_ins : nao22_x1
  PORT MAP (
    i0 => noa22_x1_4_sig,
    i1 => aux63,
    i2 => i(0),
    nq => nao22_x1_8_sig,
    vdd => vdd,
    vss => vss
  );
  noa22_x1_4_ins : noa22_x1
  PORT MAP (
    i0 => not_aux37,
    i1 => i(2),
    i2 => not_r(2),
    nq => noa22_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_7_ins : nao22_x1
  PORT MAP (
    i0 => no2_x1_8_sig,
    i1 => aux16,
    i2 => not_i(0),
    nq => nao22_x1_7_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_8_ins : no2_x1
  PORT MAP (
    i0 => r(2),
    i1 => not_aux47,
    nq => no2_x1_8_sig,
    vdd => vdd,
    vss => vss
  );
  noa22_x1_3_ins : noa22_x1
  PORT MAP (
    i0 => oa22_x2_2_sig,
    i1 => not_aux33,
    i2 => i(0),
    nq => noa22_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  oa22_x2_2_ins : oa22_x2
  PORT MAP (
    i0 => not_i(2),
    i1 => not_aux67,
    i2 => r(2),
    q => oa22_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  noa22_x1_2_ins : noa22_x1
  PORT MAP (
    i0 => oa22_x2_sig,
    i1 => not_aux43,
    i2 => not_i(0),
    nq => noa22_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  oa22_x2_ins : oa22_x2
  PORT MAP (
    i0 => not_i(2),
    i1 => not_aux60,
    i2 => not_r(2),
    q => oa22_x2_sig,
    vdd => vdd,
    vss => vss
  );
  noa22_x1_ins : noa22_x1
  PORT MAP (
    i0 => na3_x1_8_sig,
    i1 => na3_x1_7_sig,
    i2 => i(1),
    nq => noa22_x1_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_8_ins : na3_x1
  PORT MAP (
    i0 => a2_x2_7_sig,
    i1 => o2_x2_4_sig,
    i2 => o3_x2_3_sig,
    nq => na3_x1_8_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_7_ins : a2_x2
  PORT MAP (
    i0 => not_aux0,
    i1 => not_i(0),
    q => a2_x2_7_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_4_ins : o2_x2
  PORT MAP (
    i0 => not_aux38,
    i1 => not_i(2),
    q => o2_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_3_ins : o3_x2
  PORT MAP (
    i0 => not_aux108,
    i1 => not_aux38,
    i2 => aux75,
    q => o3_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_7_ins : na3_x1
  PORT MAP (
    i0 => a2_x2_6_sig,
    i1 => o2_x2_3_sig,
    i2 => o2_x2_2_sig,
    nq => na3_x1_7_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_6_ins : a2_x2
  PORT MAP (
    i0 => i(0),
    i1 => not_aux16,
    q => a2_x2_6_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_3_ins : o2_x2
  PORT MAP (
    i0 => not_aux110,
    i1 => not_aux48,
    q => o2_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_2_ins : o2_x2
  PORT MAP (
    i0 => not_aux48,
    i1 => not_i(2),
    q => o2_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  np_ins : oa2a22_x2
  PORT MAP (
    i0 => not_i(1),
    i1 => na3_x1_5_sig,
    i2 => na3_x1_3_sig,
    i3 => i(1),
    q => np,
    vdd => vdd,
    vss => vss
  );
  na3_x1_5_ins : na3_x1
  PORT MAP (
    i0 => o3_x2_2_sig,
    i1 => na3_x1_6_sig,
    i2 => o3_x2_sig,
    nq => na3_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_2_ins : o3_x2
  PORT MAP (
    i0 => i(2),
    i1 => i(0),
    i2 => not_aux76,
    q => o3_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_6_ins : na3_x1
  PORT MAP (
    i0 => not_s(2),
    i1 => not_i(2),
    i2 => nxr2_x1_sig,
    nq => na3_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  nxr2_x1_ins : nxr2_x1
  PORT MAP (
    i0 => r(2),
    i1 => i(0),
    nq => nxr2_x1_sig,
    vdd => vdd,
    vss => vss
  );
  o3_x2_ins : o3_x2
  PORT MAP (
    i0 => i(2),
    i1 => not_aux78,
    i2 => not_i(0),
    q => o3_x2_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_3_ins : na3_x1
  PORT MAP (
    i0 => na3_x1_4_sig,
    i1 => on12_x1_2_sig,
    i2 => nao22_x1_6_sig,
    nq => na3_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_4_ins : na3_x1
  PORT MAP (
    i0 => i(2),
    i1 => i(0),
    i2 => not_aux13,
    nq => na3_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  on12_x1_2_ins : on12_x1
  PORT MAP (
    i0 => not_i(0),
    i1 => aux29,
    q => on12_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_6_ins : nao22_x1
  PORT MAP (
    i0 => no2_x1_7_sig,
    i1 => a3_x2_3_sig,
    i2 => s(2),
    nq => nao22_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_7_ins : no2_x1
  PORT MAP (
    i0 => r(2),
    i1 => i(0),
    nq => no2_x1_7_sig,
    vdd => vdd,
    vss => vss
  );
  a3_x2_3_ins : a3_x2
  PORT MAP (
    i0 => i(2),
    i1 => r(2),
    i2 => i(0),
    q => a3_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  ovr_ins : oa2a22_x2
  PORT MAP (
    i0 => i(1),
    i1 => na3_x1_2_sig,
    i2 => na4_x1_sig,
    i3 => not_i(1),
    q => ovr,
    vdd => vdd,
    vss => vss
  );
  na3_x1_2_ins : na3_x1
  PORT MAP (
    i0 => noa3ao322_x1_sig,
    i1 => nao22_x1_5_sig,
    i2 => nao22_x1_4_sig,
    nq => na3_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  noa3ao322_x1_ins : noa3ao322_x1
  PORT MAP (
    i0 => on12_x1_sig,
    i1 => inv_x2_3_sig,
    i2 => aux42,
    i3 => no2_x1_6_sig,
    i4 => aux32,
    i5 => not_aux74,
    i6 => i(0),
    nq => noa3ao322_x1_sig,
    vdd => vdd,
    vss => vss
  );
  on12_x1_ins : on12_x1
  PORT MAP (
    i0 => r(2),
    i1 => aux70,
    q => on12_x1_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_3_ins : inv_x2
  PORT MAP (
    i => not_aux107,
    nq => inv_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_6_ins : no2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_aux68,
    nq => no2_x1_6_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_5_ins : nao22_x1
  PORT MAP (
    i0 => a3_x2_2_sig,
    i1 => ao22_x2_4_sig,
    i2 => not_s(2),
    nq => nao22_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  a3_x2_2_ins : a3_x2
  PORT MAP (
    i0 => not_i(0),
    i1 => not_aux56,
    i2 => o2_x2_sig,
    q => a3_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  o2_x2_ins : o2_x2
  PORT MAP (
    i0 => r(2),
    i1 => not_aux62,
    q => o2_x2_sig,
    vdd => vdd,
    vss => vss
  );
  ao22_x2_4_ins : ao22_x2
  PORT MAP (
    i0 => no3_x1_5_sig,
    i1 => not_r(2),
    i2 => a2_x2_5_sig,
    q => ao22_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  no3_x1_5_ins : no3_x1
  PORT MAP (
    i0 => not_i(2),
    i1 => not_aux68,
    i2 => not_aux67,
    nq => no3_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  a2_x2_5_ins : a2_x2
  PORT MAP (
    i0 => i(0),
    i1 => not_aux63,
    q => a2_x2_5_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_4_ins : nao22_x1
  PORT MAP (
    i0 => nao2o22_x1_sig,
    i1 => ao22_x2_3_sig,
    i2 => not_i(0),
    nq => nao22_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  nao2o22_x1_ins : nao2o22_x1
  PORT MAP (
    i0 => not_i(2),
    i1 => not_aux42,
    i2 => not_aux106,
    i3 => not_aux69,
    nq => nao2o22_x1_sig,
    vdd => vdd,
    vss => vss
  );
  ao22_x2_3_ins : ao22_x2
  PORT MAP (
    i0 => no3_x1_4_sig,
    i1 => no3_x1_3_sig,
    i2 => r(2),
    q => ao22_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  no3_x1_4_ins : no3_x1
  PORT MAP (
    i0 => inv_x2_2_sig,
    i1 => not_aux28,
    i2 => not_i(2),
    nq => no3_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_2_ins : inv_x2
  PORT MAP (
    i => aux114,
    nq => inv_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  no3_x1_3_ins : no3_x1
  PORT MAP (
    i0 => not_aux61,
    i1 => not_aux22,
    i2 => i(2),
    nq => no3_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  na4_x1_ins : na4_x1
  PORT MAP (
    i0 => nao22_x1_3_sig,
    i1 => nao22_x1_2_sig,
    i2 => nao22_x1_sig,
    i3 => ao2o22_x2_sig,
    nq => na4_x1_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_3_ins : nao22_x1
  PORT MAP (
    i0 => no2_x1_5_sig,
    i1 => no4_x1_2_sig,
    i2 => not_i(0),
    nq => nao22_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_5_ins : no2_x1
  PORT MAP (
    i0 => r(2),
    i1 => not_aux15,
    nq => no2_x1_5_sig,
    vdd => vdd,
    vss => vss
  );
  no4_x1_2_ins : no4_x1
  PORT MAP (
    i0 => not_aux113,
    i1 => aux4,
    i2 => not_aux32,
    i3 => not_aux108,
    nq => no4_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_2_ins : nao22_x1
  PORT MAP (
    i0 => no3_x1_2_sig,
    i1 => a3_x2_sig,
    i2 => s(2),
    nq => nao22_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  no3_x1_2_ins : no3_x1
  PORT MAP (
    i0 => not_aux41,
    i1 => not_aux33,
    i2 => i(0),
    nq => no3_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  a3_x2_ins : a3_x2
  PORT MAP (
    i0 => i(0),
    i1 => aux51,
    i2 => aux43,
    q => a3_x2_sig,
    vdd => vdd,
    vss => vss
  );
  nao22_x1_ins : nao22_x1
  PORT MAP (
    i0 => ao22_x2_2_sig,
    i1 => ao22_x2_sig,
    i2 => not_s(2),
    nq => nao22_x1_sig,
    vdd => vdd,
    vss => vss
  );
  ao22_x2_2_ins : ao22_x2
  PORT MAP (
    i0 => no2_x1_4_sig,
    i1 => no2_x1_3_sig,
    i2 => i(0),
    q => ao22_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_4_ins : no2_x1
  PORT MAP (
    i0 => not_aux108,
    i1 => not_aux16,
    nq => no2_x1_4_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_3_ins : no2_x1
  PORT MAP (
    i0 => r(2),
    i1 => not_aux31,
    nq => no2_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  ao22_x2_ins : ao22_x2
  PORT MAP (
    i0 => no2_x1_2_sig,
    i1 => no2_x1_sig,
    i2 => not_i(0),
    q => ao22_x2_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_2_ins : no2_x1
  PORT MAP (
    i0 => not_aux15,
    i1 => not_r(2),
    nq => no2_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  no2_x1_ins : no2_x1
  PORT MAP (
    i0 => not_aux105,
    i1 => not_aux0,
    nq => no2_x1_sig,
    vdd => vdd,
    vss => vss
  );
  ao2o22_x2_ins : ao2o22_x2
  PORT MAP (
    i0 => not_i(0),
    i1 => ao2o22_x2_2_sig,
    i2 => not_i(2),
    i3 => cin,
    q => ao2o22_x2_sig,
    vdd => vdd,
    vss => vss
  );
  ao2o22_x2_2_ins : ao2o22_x2
  PORT MAP (
    i0 => not_aux49,
    i1 => not_aux106,
    i2 => not_aux31,
    i3 => not_r(2),
    q => ao2o22_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  f3_ins : buf_x2
  PORT MAP (
    i => alu_out(3),
    q => f3,
    vdd => vdd,
    vss => vss
  );
  zero_ins : no4_x1
  PORT MAP (
    i0 => alu_out(2),
    i1 => alu_out(0),
    i2 => alu_out(1),
    i3 => alu_out(3),
    nq => zero,
    vdd => vdd,
    vss => vss
  );
  aux1_ins : a2_x2
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    q => aux1,
    vdd => vdd,
    vss => vss
  );
  aux3_ins : na2_x1
  PORT MAP (
    i0 => r(0),
    i1 => s(0),
    nq => aux3,
    vdd => vdd,
    vss => vss
  );
  aux4_ins : no2_x1
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    nq => aux4,
    vdd => vdd,
    vss => vss
  );
  aux7_ins : na2_x1
  PORT MAP (
    i0 => not_r(0),
    i1 => not_s(0),
    nq => aux7,
    vdd => vdd,
    vss => vss
  );
  aux12_ins : na2_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => not_aux1,
    nq => aux12,
    vdd => vdd,
    vss => vss
  );
  aux16_ins : an12_x1
  PORT MAP (
    i0 => r(3),
    i1 => s(3),
    q => aux16,
    vdd => vdd,
    vss => vss
  );
  aux17_ins : no2_x1
  PORT MAP (
    i0 => r(1),
    i1 => not_s(1),
    nq => aux17,
    vdd => vdd,
    vss => vss
  );
  aux19_ins : na2_x1
  PORT MAP (
    i0 => s(0),
    i1 => not_r(0),
    nq => aux19,
    vdd => vdd,
    vss => vss
  );
  aux20_ins : no2_x1
  PORT MAP (
    i0 => s(1),
    i1 => not_r(1),
    nq => aux20,
    vdd => vdd,
    vss => vss
  );
  aux21_ins : na2_x1
  PORT MAP (
    i0 => not_aux19,
    i1 => not_aux20,
    nq => aux21,
    vdd => vdd,
    vss => vss
  );
  aux23_ins : na2_x1
  PORT MAP (
    i0 => r(0),
    i1 => not_s(0),
    nq => aux23,
    vdd => vdd,
    vss => vss
  );
  aux25_ins : na2_x1
  PORT MAP (
    i0 => cin,
    i1 => not_aux24,
    nq => aux25,
    vdd => vdd,
    vss => vss
  );
  aux29_ins : no2_x1
  PORT MAP (
    i0 => not_aux28,
    i1 => not_aux19,
    nq => aux29,
    vdd => vdd,
    vss => vss
  );
  aux32_ins : no2_x1
  PORT MAP (
    i0 => r(3),
    i1 => s(3),
    nq => aux32,
    vdd => vdd,
    vss => vss
  );
  aux39_ins : na2_x1
  PORT MAP (
    i0 => not_aux38,
    i1 => not_cin,
    nq => aux39,
    vdd => vdd,
    vss => vss
  );
  aux42_ins : an12_x1
  PORT MAP (
    i0 => s(3),
    i1 => r(3),
    q => aux42,
    vdd => vdd,
    vss => vss
  );
  aux43_ins : no2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_aux42,
    nq => aux43,
    vdd => vdd,
    vss => vss
  );
  aux51_ins : na2_x1
  PORT MAP (
    i0 => r(2),
    i1 => not_aux50,
    nq => aux51,
    vdd => vdd,
    vss => vss
  );
  aux63_ins : no2_x1
  PORT MAP (
    i0 => not_aux0,
    i1 => not_i(2),
    nq => aux63,
    vdd => vdd,
    vss => vss
  );
  aux68_ins : na2_x1
  PORT MAP (
    i0 => not_aux8,
    i1 => not_cin,
    nq => aux68,
    vdd => vdd,
    vss => vss
  );
  aux70_ins : no2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_aux62,
    nq => aux70,
    vdd => vdd,
    vss => vss
  );
  aux75_ins : na2_x1
  PORT MAP (
    i0 => not_aux4,
    i1 => not_aux32,
    nq => aux75,
    vdd => vdd,
    vss => vss
  );
  aux77_ins : na2_x1
  PORT MAP (
    i0 => not_aux42,
    i1 => not_aux20,
    nq => aux77,
    vdd => vdd,
    vss => vss
  );
  aux91_ins : noa22_x1
  PORT MAP (
    i0 => not_cin,
    i1 => not_aux76,
    i2 => i(2),
    nq => aux91,
    vdd => vdd,
    vss => vss
  );
  aux98_ins : nxr2_x1
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    nq => aux98,
    vdd => vdd,
    vss => vss
  );
  aux99_ins : a2_x2
  PORT MAP (
    i0 => not_aux40,
    i1 => not_i(2),
    q => aux99,
    vdd => vdd,
    vss => vss
  );
  aux100_ins : na2_x1
  PORT MAP (
    i0 => not_aux50,
    i1 => not_i(2),
    nq => aux100,
    vdd => vdd,
    vss => vss
  );
  aux102_ins : nxr2_x1
  PORT MAP (
    i0 => r(3),
    i1 => s(3),
    nq => aux102,
    vdd => vdd,
    vss => vss
  );
  aux104_ins : no2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_aux102,
    nq => aux104,
    vdd => vdd,
    vss => vss
  );
  aux105_ins : no2_x1
  PORT MAP (
    i0 => r(2),
    i1 => i(2),
    nq => aux105,
    vdd => vdd,
    vss => vss
  );
  aux108_ins : no2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_r(2),
    nq => aux108,
    vdd => vdd,
    vss => vss
  );
  aux109_ins : na2_x1
  PORT MAP (
    i0 => i(2),
    i1 => not_r(2),
    nq => aux109,
    vdd => vdd,
    vss => vss
  );
  aux111_ins : no2_x1
  PORT MAP (
    i0 => not_aux108,
    i1 => not_aux102,
    nq => aux111,
    vdd => vdd,
    vss => vss
  );
  aux114_ins : no2_x1
  PORT MAP (
    i0 => not_aux21,
    i1 => not_aux61,
    nq => aux114,
    vdd => vdd,
    vss => vss
  );
  not_s_0_ins : inv_x2
  PORT MAP (
    i => s(0),
    nq => not_s(0),
    vdd => vdd,
    vss => vss
  );
  not_s_1_ins : inv_x2
  PORT MAP (
    i => s(1),
    nq => not_s(1),
    vdd => vdd,
    vss => vss
  );
  not_s_2_ins : inv_x2
  PORT MAP (
    i => s(2),
    nq => not_s(2),
    vdd => vdd,
    vss => vss
  );
  not_r_0_ins : inv_x2
  PORT MAP (
    i => r(0),
    nq => not_r(0),
    vdd => vdd,
    vss => vss
  );
  not_r_1_ins : inv_x2
  PORT MAP (
    i => r(1),
    nq => not_r(1),
    vdd => vdd,
    vss => vss
  );
  not_r_2_ins : inv_x2
  PORT MAP (
    i => r(2),
    nq => not_r(2),
    vdd => vdd,
    vss => vss
  );
  not_i_0_ins : inv_x2
  PORT MAP (
    i => i(0),
    nq => not_i(0),
    vdd => vdd,
    vss => vss
  );
  not_i_1_ins : inv_x2
  PORT MAP (
    i => i(1),
    nq => not_i(1),
    vdd => vdd,
    vss => vss
  );
  not_i_2_ins : inv_x2
  PORT MAP (
    i => i(2),
    nq => not_i(2),
    vdd => vdd,
    vss => vss
  );
  not_cin_ins : inv_x2
  PORT MAP (
    i => cin,
    nq => not_cin,
    vdd => vdd,
    vss => vss
  );
  not_aux4_ins : inv_x2
  PORT MAP (
    i => aux4,
    nq => not_aux4,
    vdd => vdd,
    vss => vss
  );
  not_aux3_ins : inv_x2
  PORT MAP (
    i => aux3,
    nq => not_aux3,
    vdd => vdd,
    vss => vss
  );
  not_aux5_ins : a2_x2
  PORT MAP (
    i0 => not_aux3,
    i1 => not_aux4,
    q => not_aux5,
    vdd => vdd,
    vss => vss
  );
  not_aux1_ins : inv_x2
  PORT MAP (
    i => aux1,
    nq => not_aux1,
    vdd => vdd,
    vss => vss
  );
  not_aux0_ins : na2_x1
  PORT MAP (
    i0 => r(3),
    i1 => s(3),
    nq => not_aux0,
    vdd => vdd,
    vss => vss
  );
  not_aux7_ins : inv_x2
  PORT MAP (
    i => aux7,
    nq => not_aux7,
    vdd => vdd,
    vss => vss
  );
  not_aux8_ins : no2_x1
  PORT MAP (
    i0 => not_aux7,
    i1 => aux4,
    nq => not_aux8,
    vdd => vdd,
    vss => vss
  );
  not_aux68_ins : inv_x2
  PORT MAP (
    i => aux68,
    nq => not_aux68,
    vdd => vdd,
    vss => vss
  );
  not_aux74_ins : a2_x2
  PORT MAP (
    i0 => no4_x1_sig,
    i1 => aux68,
    q => not_aux74,
    vdd => vdd,
    vss => vss
  );
  no4_x1_ins : no4_x1
  PORT MAP (
    i0 => aux12,
    i1 => r(2),
    i2 => not_aux5,
    i3 => not_i(2),
    nq => no4_x1_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux32_ins : inv_x2
  PORT MAP (
    i => aux32,
    nq => not_aux32,
    vdd => vdd,
    vss => vss
  );
  not_aux42_ins : inv_x2
  PORT MAP (
    i => aux42,
    nq => not_aux42,
    vdd => vdd,
    vss => vss
  );
  not_aux20_ins : inv_x2
  PORT MAP (
    i => aux20,
    nq => not_aux20,
    vdd => vdd,
    vss => vss
  );
  not_aux23_ins : inv_x2
  PORT MAP (
    i => aux23,
    nq => not_aux23,
    vdd => vdd,
    vss => vss
  );
  not_aux24_ins : a2_x2
  PORT MAP (
    i0 => not_aux20,
    i1 => aux23,
    q => not_aux24,
    vdd => vdd,
    vss => vss
  );
  not_aux61_ins : a2_x2
  PORT MAP (
    i0 => not_aux24,
    i1 => not_cin,
    q => not_aux61,
    vdd => vdd,
    vss => vss
  );
  not_aux19_ins : inv_x2
  PORT MAP (
    i => aux19,
    nq => not_aux19,
    vdd => vdd,
    vss => vss
  );
  not_aux21_ins : inv_x2
  PORT MAP (
    i => aux21,
    nq => not_aux21,
    vdd => vdd,
    vss => vss
  );
  not_aux17_ins : inv_x2
  PORT MAP (
    i => aux17,
    nq => not_aux17,
    vdd => vdd,
    vss => vss
  );
  not_aux16_ins : inv_x2
  PORT MAP (
    i => aux16,
    nq => not_aux16,
    vdd => vdd,
    vss => vss
  );
  not_aux28_ins : na2_x1
  PORT MAP (
    i0 => not_aux16,
    i1 => not_aux17,
    nq => not_aux28,
    vdd => vdd,
    vss => vss
  );
  not_aux22_ins : o3_x2
  PORT MAP (
    i0 => not_aux21,
    i1 => not_aux16,
    i2 => aux17,
    q => not_aux22,
    vdd => vdd,
    vss => vss
  );
  not_aux48_ins : a2_x2
  PORT MAP (
    i0 => not_aux17,
    i1 => aux19,
    q => not_aux48,
    vdd => vdd,
    vss => vss
  );
  not_aux69_ins : a2_x2
  PORT MAP (
    i0 => cin,
    i1 => not_aux48,
    q => not_aux69,
    vdd => vdd,
    vss => vss
  );
  not_aux54_ins : a2_x2
  PORT MAP (
    i0 => not_aux23,
    i1 => not_aux17,
    q => not_aux54,
    vdd => vdd,
    vss => vss
  );
  not_aux105_ins : inv_x2
  PORT MAP (
    i => aux105,
    nq => not_aux105,
    vdd => vdd,
    vss => vss
  );
  not_aux106_ins : o4_x2
  PORT MAP (
    i0 => not_aux54,
    i1 => not_aux105,
    i2 => not_aux42,
    i3 => aux20,
    q => not_aux106,
    vdd => vdd,
    vss => vss
  );
  not_aux60_ins : ao2o22_x2
  PORT MAP (
    i0 => s(1),
    i1 => a2_x2_4_sig,
    i2 => not_aux19,
    i3 => not_r(1),
    q => not_aux60,
    vdd => vdd,
    vss => vss
  );
  a2_x2_4_ins : a2_x2
  PORT MAP (
    i0 => not_aux19,
    i1 => not_r(1),
    q => a2_x2_4_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux62_ins : no2_x1
  PORT MAP (
    i0 => not_aux61,
    i1 => not_aux60,
    nq => not_aux62,
    vdd => vdd,
    vss => vss
  );
  not_aux107_ins : o2_x2
  PORT MAP (
    i0 => i(0),
    i1 => not_s(2),
    q => not_aux107,
    vdd => vdd,
    vss => vss
  );
  not_aux67_ins : ao2o22_x2
  PORT MAP (
    i0 => s(1),
    i1 => a2_x2_3_sig,
    i2 => not_aux3,
    i3 => r(1),
    q => not_aux67,
    vdd => vdd,
    vss => vss
  );
  a2_x2_3_ins : a2_x2
  PORT MAP (
    i0 => r(1),
    i1 => not_aux3,
    q => a2_x2_3_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux63_ins : inv_x2
  PORT MAP (
    i => aux63,
    nq => not_aux63,
    vdd => vdd,
    vss => vss
  );
  not_aux56_ins : xr2_x1
  PORT MAP (
    i0 => aux16,
    i1 => i(2),
    q => not_aux56,
    vdd => vdd,
    vss => vss
  );
  not_aux31_ins : noa22_x1
  PORT MAP (
    i0 => aux29,
    i1 => i(2),
    i2 => no3_x1_sig,
    nq => not_aux31,
    vdd => vdd,
    vss => vss
  );
  no3_x1_ins : no3_x1
  PORT MAP (
    i0 => inv_x2_sig,
    i1 => not_aux22,
    i2 => i(2),
    nq => no3_x1_sig,
    vdd => vdd,
    vss => vss
  );
  inv_x2_ins : inv_x2
  PORT MAP (
    i => aux25,
    nq => inv_x2_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux49_ins : a2_x2
  PORT MAP (
    i0 => not_aux48,
    i1 => not_cin,
    q => not_aux49,
    vdd => vdd,
    vss => vss
  );
  not_aux38_ins : a2_x2
  PORT MAP (
    i0 => not_aux1,
    i1 => aux3,
    q => not_aux38,
    vdd => vdd,
    vss => vss
  );
  not_aux39_ins : inv_x2
  PORT MAP (
    i => aux39,
    nq => not_aux39,
    vdd => vdd,
    vss => vss
  );
  not_aux52_ins : a2_x2
  PORT MAP (
    i0 => not_aux7,
    i1 => not_aux1,
    q => not_aux52,
    vdd => vdd,
    vss => vss
  );
  not_aux113_ins : o2_x2
  PORT MAP (
    i0 => not_aux52,
    i1 => not_aux39,
    q => not_aux113,
    vdd => vdd,
    vss => vss
  );
  not_aux108_ins : inv_x2
  PORT MAP (
    i => aux108,
    nq => not_aux108,
    vdd => vdd,
    vss => vss
  );
  not_aux13_ins : o2_x2
  PORT MAP (
    i0 => not_aux3,
    i1 => aux12,
    q => not_aux13,
    vdd => vdd,
    vss => vss
  );
  not_aux9_ins : a2_x2
  PORT MAP (
    i0 => cin,
    i1 => not_aux8,
    q => not_aux9,
    vdd => vdd,
    vss => vss
  );
  not_aux15_ins : ao2o22_x2
  PORT MAP (
    i0 => not_aux5,
    i1 => o4_x2_sig,
    i2 => not_aux13,
    i3 => not_i(2),
    q => not_aux15,
    vdd => vdd,
    vss => vss
  );
  o4_x2_ins : o4_x2
  PORT MAP (
    i0 => not_aux9,
    i1 => i(2),
    i2 => not_aux0,
    i3 => aux1,
    q => o4_x2_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux47_ins : ao2o22_x2
  PORT MAP (
    i0 => not_s(1),
    i1 => a2_x2_2_sig,
    i2 => not_aux23,
    i3 => r(1),
    q => not_aux47,
    vdd => vdd,
    vss => vss
  );
  a2_x2_2_ins : a2_x2
  PORT MAP (
    i0 => r(1),
    i1 => not_aux23,
    q => a2_x2_2_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux50_ins : o2_x2
  PORT MAP (
    i0 => not_aux49,
    i1 => not_aux47,
    q => not_aux50,
    vdd => vdd,
    vss => vss
  );
  not_aux43_ins : inv_x2
  PORT MAP (
    i => aux43,
    nq => not_aux43,
    vdd => vdd,
    vss => vss
  );
  not_aux37_ins : ao2o22_x2
  PORT MAP (
    i0 => not_s(1),
    i1 => a2_x2_sig,
    i2 => not_aux7,
    i3 => not_r(1),
    q => not_aux37,
    vdd => vdd,
    vss => vss
  );
  a2_x2_ins : a2_x2
  PORT MAP (
    i0 => not_aux7,
    i1 => not_r(1),
    q => a2_x2_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux40_ins : o2_x2
  PORT MAP (
    i0 => not_aux39,
    i1 => not_aux37,
    q => not_aux40,
    vdd => vdd,
    vss => vss
  );
  not_aux41_ins : a2_x2
  PORT MAP (
    i0 => not_aux40,
    i1 => not_r(2),
    q => not_aux41,
    vdd => vdd,
    vss => vss
  );
  not_aux33_ins : o2_x2
  PORT MAP (
    i0 => i(2),
    i1 => not_aux32,
    q => not_aux33,
    vdd => vdd,
    vss => vss
  );
  not_aux77_ins : inv_x2
  PORT MAP (
    i => aux77,
    nq => not_aux77,
    vdd => vdd,
    vss => vss
  );
  not_aux78_ins : a2_x2
  PORT MAP (
    i0 => not_aux77,
    i1 => aux23,
    q => not_aux78,
    vdd => vdd,
    vss => vss
  );
  not_aux76_ins : an12_x1
  PORT MAP (
    i0 => aux75,
    i1 => aux7,
    q => not_aux76,
    vdd => vdd,
    vss => vss
  );
  not_aux110_ins : o2_x2
  PORT MAP (
    i0 => not_aux105,
    i1 => aux77,
    q => not_aux110,
    vdd => vdd,
    vss => vss
  );
  not_aux89_ins : nxr2_x1
  PORT MAP (
    i0 => a4_x2_sig,
    i1 => i(2),
    nq => not_aux89,
    vdd => vdd,
    vss => vss
  );
  a4_x2_ins : a4_x2
  PORT MAP (
    i0 => na3_x1_sig,
    i1 => na2_x1_2_sig,
    i2 => not_aux16,
    i3 => na2_x1_sig,
    q => a4_x2_sig,
    vdd => vdd,
    vss => vss
  );
  na3_x1_ins : na3_x1
  PORT MAP (
    i0 => s(1),
    i1 => not_aux42,
    i2 => not_r(1),
    nq => na3_x1_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_2_ins : na2_x1
  PORT MAP (
    i0 => not_aux77,
    i1 => not_aux19,
    nq => na2_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  na2_x1_ins : na2_x1
  PORT MAP (
    i0 => not_aux78,
    i1 => not_cin,
    nq => na2_x1_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux79_ins : o2_x2
  PORT MAP (
    i0 => not_aux52,
    i1 => aux75,
    q => not_aux79,
    vdd => vdd,
    vss => vss
  );
  not_aux81_ins : o2_x2
  PORT MAP (
    i0 => i(2),
    i1 => not_aux50,
    q => not_aux81,
    vdd => vdd,
    vss => vss
  );
  not_aux80_ins : o2_x2
  PORT MAP (
    i0 => i(2),
    i1 => not_aux40,
    q => not_aux80,
    vdd => vdd,
    vss => vss
  );
  not_aux115_ins : o2_x2
  PORT MAP (
    i0 => not_aux54,
    i1 => not_aux49,
    q => not_aux115,
    vdd => vdd,
    vss => vss
  );
  not_aux93_ins : xr2_x1
  PORT MAP (
    i0 => xr2_x1_3_sig,
    i1 => cin,
    q => not_aux93,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_3_ins : xr2_x1
  PORT MAP (
    i0 => s(0),
    i1 => r(0),
    q => xr2_x1_3_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux95_ins : xr2_x1
  PORT MAP (
    i0 => aux19,
    i1 => xr2_x1_2_sig,
    q => not_aux95,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_2_ins : xr2_x1
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    q => xr2_x1_2_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux97_ins : xr2_x1
  PORT MAP (
    i0 => xr2_x1_sig,
    i1 => not_aux23,
    q => not_aux97,
    vdd => vdd,
    vss => vss
  );
  xr2_x1_ins : xr2_x1
  PORT MAP (
    i0 => r(1),
    i1 => s(1),
    q => xr2_x1_sig,
    vdd => vdd,
    vss => vss
  );
  not_aux101_ins : xr2_x1
  PORT MAP (
    i0 => aux70,
    i1 => r(2),
    q => not_aux101,
    vdd => vdd,
    vss => vss
  );
  not_aux102_ins : inv_x2
  PORT MAP (
    i => aux102,
    nq => not_aux102,
    vdd => vdd,
    vss => vss
  );
  not_aux104_ins : inv_x2
  PORT MAP (
    i => aux104,
    nq => not_aux104,
    vdd => vdd,
    vss => vss
  );
  not_aux112_ins : na2_x1
  PORT MAP (
    i0 => not_aux102,
    i1 => aux105,
    nq => not_aux112,
    vdd => vdd,
    vss => vss
  );
  not_aux103_ins : na2_x1
  PORT MAP (
    i0 => not_aux102,
    i1 => not_i(2),
    nq => not_aux103,
    vdd => vdd,
    vss => vss
  );
END RTL;
